rds_record_name   = "db.aurouz-test-net.local"
redis_record_name = "redis.aurouz-test-net.local"
environment       = "test"
created_by        = "Ravi Teja Nimma"
region            = "ap-east-1"
aws_account_id    = "594621557419"
